Repository prgrms-aibe-devcourse/AIBE1-FinalProject-Team01-BE, pull requests merged in 2025-07, with the labels that each got.

#221 Chore: JaCoCo 테스트 커버리지 추가 #203
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/jooq.yml
  .github/workflows/test.yml
  build.gradle
  gradle.properties
Labels: Chore

#227 Feat: Topic enum 확장 및 관련 테스트 수정 #226
  src/main/java/kr/co/amateurs/server/domain/entity/user/enums/Topic.java
  src/main/resources/db/migration/V12__expand_topic_column_size.sql
  src/test/java/kr/co/amateurs/server/controller/user/UserControllerTest.java
  src/test/java/kr/co/amateurs/server/fixture/common/UserTestFixture.java
  src/test/java/kr/co/amateurs/server/service/UserServiceTest.java
  src/test/java/kr/co/amateurs/server/service/auth/AuthServiceTest.java
Labels: Feat

#213 Refactor: 프로필 이미지 S3 저장 #206
  src/main/java/kr/co/amateurs/server/domain/common/ErrorCode.java
  src/main/java/kr/co/amateurs/server/service/auth/CustomOAuth2UserService.java
  src/main/java/kr/co/amateurs/server/service/file/FileService.java
  src/main/java/kr/co/amateurs/server/utils/file/DownloadedMultipartFile.java
Labels: Refactor

#219 Fix: 이미지 삭제 스케줄러 수정, 이미지 타입 밸리데이션 강화
  src/main/java/kr/co/amateurs/server/service/file/FileService.java
  src/main/java/kr/co/amateurs/server/service/file/UnreferencedImageClearScheduler.java
Labels: Fix

#230 Chore: OpenTelemetry + Tempo 분산 트레이싱 구축 #229
  .github/workflows/test.yml
  build.gradle
  docker/loki/loki-config.yml
  docker/otel-collector/docker-compose.yml
  docker/otel-collector/otel-collector-config.yml
  docker/prometheus/docker-compose.yml
  docker/prometheus/prometheus.yml
  docker/tempo/docker-compose.yml
  docker/tempo/tempo-config.yml
  src/main/java/kr/co/amateurs/server/config/AsyncConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: Chore

#233 Fix : 토큰 재발급 API 쿠키 기반으로 수정 #232
  src/main/java/kr/co/amateurs/server/controller/auth/AuthController.java
  src/main/java/kr/co/amateurs/server/domain/dto/user/UserProfileResponseDTO.java
  src/main/java/kr/co/amateurs/server/service/auth/AuthService.java
  src/test/java/kr/co/amateurs/server/controller/auth/AuthControllerTest.java
  src/test/java/kr/co/amateurs/server/service/auth/AuthServiceTest.java
Labels: Fix

#235 Fix: BoardId 사용으로 인한 AI 로직 변경(1차)
  src/main/java/kr/co/amateurs/server/controller/ai/AiController.java
  src/main/java/kr/co/amateurs/server/controller/ai/AiDevController.java
  src/main/java/kr/co/amateurs/server/domain/dto/ai/PostRecommendationResponse.java
  src/main/java/kr/co/amateurs/server/domain/dto/post/PopularPostRequest.java
  src/main/java/kr/co/amateurs/server/domain/dto/post/PopularPostResponse.java
  src/main/java/kr/co/amateurs/server/domain/entity/ai/RecommendedPost.java
  src/main/java/kr/co/amateurs/server/domain/entity/post/PopularPost.java
  src/main/java/kr/co/amateurs/server/repository/ai/AiRecommendPostRepository.java
  src/main/java/kr/co/amateurs/server/repository/post/PopularPostRepository.java
  src/main/java/kr/co/amateurs/server/repository/post/PostJooqRepository.java
  src/main/java/kr/co/amateurs/server/service/ai/AiPostAnalysis.java
  src/main/java/kr/co/amateurs/server/service/ai/AiProfileService.java
  src/main/java/kr/co/amateurs/server/service/ai/PostEmbeddingService.java
  src/main/java/kr/co/amateurs/server/service/ai/PostRecommendService.java
  src/main/java/kr/co/amateurs/server/service/post/PopularPostService.java
  src/main/java/kr/co/amateurs/server/service/post/PostService.java
  src/main/resources/db/migration/V13__add_board_id_to_popular_posts.sql
  src/main/resources/db/migration/V14__add_board_type_and_board_id_to_recommended_posts.sql
  src/test/java/kr/co/amateurs/server/controller/ai/AiControllerTest.java
  src/test/java/kr/co/amateurs/server/fixture/post/PopularPostRequestFixture.java
  src/test/java/kr/co/amateurs/server/service/ai/AiProfileServiceTest.java
  src/test/java/kr/co/amateurs/server/service/ai/PostRecommendServiceTest.java
  src/test/java/kr/co/amateurs/server/service/it/ITServiceTest.java
  src/test/java/kr/co/amateurs/server/service/together/GatheringServiceTest.java
  src/test/java/kr/co/amateurs/server/service/together/MarketServiceTest.java
  src/test/java/kr/co/amateurs/server/service/together/MatchServiceTest.java
Labels: Fix

#242 Refactor: 인기글 & AI 추천 시스템 성능 최적화
  src/main/java/kr/co/amateurs/server/config/RedisConfig.java
  src/main/java/kr/co/amateurs/server/controller/verify/VerifyController.java
  src/main/java/kr/co/amateurs/server/domain/dto/post/PopularPostResponse.java
  src/main/java/kr/co/amateurs/server/domain/entity/post/PopularPost.java
  src/main/java/kr/co/amateurs/server/domain/entity/user/User.java
  src/main/java/kr/co/amateurs/server/repository/post/PopularPostRepository.java
  src/main/java/kr/co/amateurs/server/service/UserService.java
  src/main/java/kr/co/amateurs/server/service/ai/PostEmbeddingManageService.java
  src/main/java/kr/co/amateurs/server/service/community/CommunityService.java
  src/main/java/kr/co/amateurs/server/service/it/ITService.java
  src/main/java/kr/co/amateurs/server/service/post/PopularPostCacheService.java
  src/main/java/kr/co/amateurs/server/service/post/PopularPostService.java
  src/main/java/kr/co/amateurs/server/service/project/ProjectService.java
  src/main/java/kr/co/amateurs/server/service/scheduler/AiPostRecommendScehdularService.java
  src/main/java/kr/co/amateurs/server/service/scheduler/EmbeddingCleanupSchedulerService.java
  src/main/java/kr/co/amateurs/server/service/together/GatheringService.java
  src/main/java/kr/co/amateurs/server/service/together/MarketService.java
  src/main/java/kr/co/amateurs/server/service/together/MatchService.java
  src/main/java/kr/co/amateurs/server/service/verify/VerifyService.java
  src/main/resources/db/migration/V13__add_board_id_to_popular_posts.sql
  src/main/resources/db/migration/V3__create_popular_posts_table.sql
  src/test/java/kr/co/amateurs/server/fixture/post/PopularPostRequestFixture.java
  src/test/java/kr/co/amateurs/server/service/community/CommunityServiceTest.java
  src/test/java/kr/co/amateurs/server/service/post/PopularPostServiceTest.java
  src/test/java/kr/co/amateurs/server/service/together/MatchServiceTest.java
Labels: Feat

#249 Refactor: Spring Security HTTP 요청 권한 설정 분리 및 리팩토링 #248
  docker/tempo/docker-compose.yml
  docker/tempo/tempo-config.yml
  src/main/java/kr/co/amateurs/server/config/SecurityConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/AiAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/AlarmAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/AuthAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/BookmarkAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/CommentAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/CommunityAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/CustomAuthorizeHttpRequestsConfigurer.java
  src/main/java/kr/co/amateurs/server/config/auth/http/DirectMessageAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/FileAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/FollowAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/ITAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/LikeAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/PostAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/ProjectAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/ReportAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/SseAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/TogetherAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/UserAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/config/auth/http/VerifyAuthorizeHttpRequestsConfig.java
  src/test/java/kr/co/amateurs/server/controller/auth/AuthControllerTest.java
  src/test/java/kr/co/amateurs/server/controller/comment/CommentControllerTest.java
  src/test/java/kr/co/amateurs/server/controller/user/UserControllerTest.java
Labels: Refactor

#256 Fix: 배포 수강생 인증 안되는 오류 해결
  build.gradle
  src/main/java/kr/co/amateurs/server/config/auth/http/AiAdminAuthorizeHttpRequestsConfig.java
  src/main/java/kr/co/amateurs/server/controller/ai/AiAdminController.java
  src/main/java/kr/co/amateurs/server/domain/event/VerificationEvent.java
  src/main/java/kr/co/amateurs/server/service/ai/AiPostAnalysis.java
  src/main/java/kr/co/amateurs/server/service/verify/VerifyService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: Fix

#262 Fix: 초기 프로필 생성 비동기 이벤트 처리
  src/main/java/kr/co/amateurs/server/domain/event/AiProfileEvent.java
  src/main/java/kr/co/amateurs/server/service/ai/AiProfileService.java
  src/main/java/kr/co/amateurs/server/service/auth/AuthService.java
Labels: Fix

#263 Test: PasswordReset 기능 테스트 코드 완성 #260
  src/test/java/kr/co/amateurs/server/config/TestEmailService.java
  src/test/java/kr/co/amateurs/server/controller/auth/AuthControllerTest.java
  src/test/java/kr/co/amateurs/server/fixture/common/UserTestFixture.java
  src/test/java/kr/co/amateurs/server/service/auth/PasswordResetServiceTest.java
Labels: Test

#269 Feat: 프로필 모달 DTO 수정
  src/main/java/kr/co/amateurs/server/domain/dto/user/UserModalInfoResponseDTO.java
  src/main/java/kr/co/amateurs/server/repository/user/UserJooqRepository.java
  src/main/java/kr/co/amateurs/server/service/UserService.java
Labels: Feat

#277 Chore: 메인 브랜치 병합 #276
  src/main/java/kr/co/amateurs/server/annotation/alarmtrigger/creator/CommentAlarmCreator.java
  src/main/java/kr/co/amateurs/server/controller/community/CommunityController.java
  src/main/java/kr/co/amateurs/server/controller/it/ITController.java
  src/main/java/kr/co/amateurs/server/controller/project/ProjectController.java
  src/main/java/kr/co/amateurs/server/controller/together/GatheringController.java
  src/main/java/kr/co/amateurs/server/controller/together/MarketController.java
  src/main/java/kr/co/amateurs/server/controller/together/MatchController.java
  src/main/java/kr/co/amateurs/server/domain/dto/alarm/AlarmDTO.java
  src/main/java/kr/co/amateurs/server/domain/entity/alarm/metadata/CommentMetaData.java
  src/main/java/kr/co/amateurs/server/domain/entity/auth/PasswordResetToken.java
  src/main/java/kr/co/amateurs/server/service/scheduler/ViewCountScheduler.java
  src/main/java/kr/co/amateurs/server/utils/ClientIPUtils.java
  src/test/java/kr/co/amateurs/server/controller/comment/CommentControllerTest.java
  src/test/java/kr/co/amateurs/server/fixture/alarm/AlarmTestFixture.java
Labels: Chore

#279 Style: 로그 제거
  src/main/java/kr/co/amateurs/server/controller/ai/AiController.java
  src/main/java/kr/co/amateurs/server/service/post/PopularPostCacheService.java
  src/main/java/kr/co/amateurs/server/service/post/PopularPostService.java
Labels: Style

#281 Feat: UserProfileResponseDTO에 필드 추가
  src/main/java/kr/co/amateurs/server/domain/dto/user/UserProfileResponseDTO.java
Labels: Feat

#282 Chore: 프로젝트 메인 브랜치 병합 #276
  .github/badges/branches.svg
  .github/badges/coverage-summary.json
  .github/badges/jacoco.svg
  .github/workflows/test.yml
  src/main/java/kr/co/amateurs/server/controller/ai/AiController.java
  src/main/java/kr/co/amateurs/server/domain/dto/user/UserProfileResponseDTO.java
  src/main/java/kr/co/amateurs/server/service/post/PopularPostCacheService.java
  src/main/java/kr/co/amateurs/server/service/post/PopularPostService.java
Labels: Chore

#285 Chore: 메인 브랜치 병합 #276
  .github/badges/coverage-summary.json
  src/main/java/kr/co/amateurs/server/service/verify/VerifyService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/resources/application-test.yml
Labels: Chore

#290 Chore: 메인 브랜치 병합 #276
  .github/badges/branches.svg
  .github/badges/coverage-summary.json
  .github/badges/jacoco.svg
  README.md
  src/main/java/kr/co/amateurs/server/domain/dto/directmessage/DirectMessageRoomResponse.java
  src/main/java/kr/co/amateurs/server/domain/entity/directmessage/Participant.java
  src/main/java/kr/co/amateurs/server/service/alarm/SseService.java
  src/main/java/kr/co/amateurs/server/service/post/ViewCountService.java
Labels: Chore
